### ISSUE TITLE
Appcenter Release?

### ISSUE THREAD

**Issue by Hedronmx** [avojak/iridium#1]
Are you planning on releasing this to the appcenter?

**Comment by avojak** [comment]
That's the plan, yes. I'm not sure when that will happen though, since I'm just working on this in my free time at night or on the weekends.

**Comment by Hedronmx** [comment]
That's awesome! Ill be waiting for the release. Thanks for your time.

**Comment by avojak** [comment]
Great! I've added a quick checklist to the README to (kinda) gauge my progress through key features. Ideally all of them would be completed before releasing to the AppCenter, but they're not all critical.
