### ISSUE TITLE
Use a large headerbar with colour icons 

### ISSUE THREAD

**Issue by hanaral** [avojak/iridium#123]
**Is your feature request related to a problem? Please describe.**
The general theme with elementary's own apps is to have a larger headerbar with colour icons or a thin header with symbolic, right now Iridium has a phat headerbar with symbolic icons, so I think it's a bit of a missed opportunity 

**Describe the solution you'd like**
~~I personally find having compact headerbars with symbolic icons to be better taste if the header doesn't have more than 2 buttons~~
Use coloured icons for the headerbar buttons

**Describe alternatives you've considered**
~~As I mentioned you can also use a bigger header with coloured icons, which can give it some life, so that's also an option~~

**Additional context**
~~This app doesn't have to follow guidelines precisely, but it would be cool to see another app aside from Terminal using a more compact headerbar~~

Edit: I should've seen that it uses subtitles

**Comment by avojak** [comment]
Thanks for the feedback! I'll have to look into this a bit more - I personally prefer the symbolic icons, however I don't want to cause inconsistencies. It might be possible to default to the color icons, but allow switching to symbolic (I think Akira does this?)

**Comment by hanaral** [comment]
I think it would be better to fit the HIG; choose one and stick with it, and rely on elementary to provide an accessibility setting that toggles smyb. icons for all headers. Again, it up to you (you aren't committing a crime by doing this lol)
My branch uses the elementary styled colour icons and it looks pretty good imo

**Comment by Suzie97** [comment]
I would go with hi color icons on the header bar too. It will be consistent with other elementary apps.

**Comment by avojak** [comment]
![Screenshot from 2021-12-07 17 46 38@2x](https://user-images.githubusercontent.com/3663899/145128515-3f101be2-e87a-4488-829e-3d94049edad6.png)

Using non-symbolic icons in the header bar. Also moved the + icon to an action bar in the side panel to be a bit more consistent as well. The menu is the same as before.
