### ISSUE TITLE
Use libhandy

### ISSUE THREAD

**Issue by Suzie97** [avojak/iridium#155]
I suggest that the app should be updated to use a handy window and a handy headerbar. That would make the app window rounded and thus making it more consistent with the current elementary style This is something that can be done with plain gtk too.

 But in the future, some multi touch gesture goodies can also be implemented with handy.

**Comment by Suzie97** [comment]
I tried implementing this and the app looked nice and rounded. But the window couldn't be dragged from the headerbar, after doing so.

@avojak any ideas on why this could happen? I didn't really research on the code to see the issue.

**Comment by avojak** [comment]
I'm not sure what you mean by the application window not being rounded - it is, as shown in the screenshots. Are you doing any customization to the elementary theme?

**Comment by Suzie97** [comment]
![Screenshot from 2021-07-18 21-13-41](https://user-images.githubusercontent.com/68198116/126073479-cbc9e599-5f87-4d2e-bc65-8bf521ed9171.png)

The bottom corners are not rounded. 

![Screenshot from 2021-07-18 21-14-07](https://user-images.githubusercontent.com/68198116/126073496-5d9b24e6-6160-4c3b-9e86-02c44dbc0182.png)

This is the mail app for reference, in which all the four corners of the window are rounded.

**Comment by Suzie97** [comment]
> I'm not sure what you mean by the application window not being rounded - it is, as shown in the screenshots. Are you doing any customization to the elementary theme?

No I'm not using a custom theme.

**Comment by avojak** [comment]
Ah I see - thanks!

**Comment by avojak** [comment]
Need to use `Hdy.init()` which will resolve not being able to drag the window when using the Hdy.HeaderBar. 

(@Suzie97 FYI)
