### ISSUE TITLE
Add option to join existing IRC channel to the welcome view

### ISSUE THREAD

**Issue by Suzie97** [avojak/iridium#156]
At the moment, the app only shows the option to create a new server in the welcome view. It should also display the option to join an existing server, which is the same option that can be accessed from the plus button at the headerbar.

**Comment by avojak** [comment]
So I'm a little confused about what you're suggesting here. The current behavior with the welcome view and the plus button is the same. I thought you were suggesting adding the ability to join predefined servers (which I might already have an open issue for?), and that's something I've been hoping to do for a while. It's a feature that I liked in Hexchat.

**Comment by avojak** [comment]
I like the idea of having pre-defined servers available, but am pushing out to the next release because I'd like to get 1.4.0 out soon.
