### ISSUE TITLE
Unable to join existing IRC channel

### ISSUE THREAD

**Issue by Suzie97** [avojak/iridium#157]
**Describe the bug**
Right now, I cannot join existing IRC channels.

**Screenshots**
![Screenshot from 2021-07-18 20-54-30](https://user-images.githubusercontent.com/68198116/126074151-b30e3d9c-20c1-4fcf-804a-ef35c6357f50.png)

**Environment (please complete the following information):**
![Screenshot from 2021-07-18 21-34-16](https://user-images.githubusercontent.com/68198116/126074172-82263364-40ea-4c6f-9f6f-f8a8e622c673.png)

Is this a planned feature? Or a bug?

**Comment by avojak** [comment]
Can you provide a bit more information on what actions you took leading up to that point? 

Were you connected to a server first? Before joining the channel you need to have a server connection, and since the drop down is greyed out I suspect there wasn't a connection. It would be good enhancement to disable the join channel option if there isn't a server connection though.

**Comment by Suzie97** [comment]
> Can you provide a bit more information on what actions you took leading up to that point?
> 
> Were you connected to a server first? Before joining the channel you need to have a server connection, and since the drop down is greyed out I suspect there wasn't a connection. It would be good enhancement to disable the join channel option if there isn't a server connection though.

Can that message be specified in the app UI? 

![Screenshot from 2021-07-18 21-51-28](https://user-images.githubusercontent.com/68198116/126074712-ce5a0250-3317-4782-b80f-bc504663fdc6.png)

Something similar to this, but in this case, the message should be printed in red.

**Comment by avojak** [comment]
It could, although I think not allowing the user to open that dialog in the first place is a bit simpler than adding a message to it.

**Comment by avojak** [comment]
And just to be clear, did you have an open server connection or no? If not I'd like to close this as a non-issue. Discussion of disabling the join channel option should go in a separate issue.

**Comment by Suzie97** [comment]
> And just to be clear, did you have an open server connection or no? If not I'd like to close this as a non-issue. Discussion of disabling the join channel option should go in a separate issue.

Yeah, I didn't setup the server. After setting up, it works.
