### ISSUE TITLE
Building for Debian 11 with pbuilder fails

### ISSUE THREAD

**Issue by SwampRabbit** [avojak/iridium#158]
**Describe the bug**
Building for Debian 11 with pbuilder fails.

**To Reproduce**
build package with pbuilder for Debian 11

**Expected behavior**
Build should complete without errors.

**Environment (please complete the following information):**
 - OS Version: Debian 11 Bullseye
 - Iridium Version 1.2.0 release

**Additional context**
I saw libgtksourceview-4-dev was now needed over libgtksourceview-3.0-dev, however, I took care of that.

Are there any other build or runtime dependency bumps needed?  libgranite is at 5.5.0 in Bullseye.
Or could the issue be something else?

```
../src/Widgets/Dialogs/ChannelJoinDialog.vala:22.50-22.63: error: The type name `Granite.Dialog' could not be found
public class Iridium.Widgets.ChannelJoinDialog : Granite.Dialog {
                                                 ^^^^^^^^^^^^^^
../src/Widgets/Dialogs/ChannelTopicEditDialog.vala:22.55-22.68: error: The type name `Granite.Dialog' could not be found
public class Iridium.Widgets.ChannelTopicEditDialog : Granite.Dialog {
                                                      ^^^^^^^^^^^^^^
../src/Widgets/Dialogs/EditServerConnectionDialog.vala:22.59-22.72: error: The type name `Granite.Dialog' could not be found
public class Iridium.Widgets.EditServerConnectionDialog : Granite.Dialog {
                                                          ^^^^^^^^^^^^^^
../src/Widgets/Dialogs/ManageConnectionsDialog.vala:22.56-22.69: error: The type name `Granite.Dialog' could not be found
public class Iridium.Widgets.ManageConnectionsDialog : Granite.Dialog {
                                                       ^^^^^^^^^^^^^^
../src/Widgets/Dialogs/NicknameEditDialog.vala:22.51-22.64: error: The type name `Granite.Dialog' could not be found
public class Iridium.Widgets.NicknameEditDialog : Granite.Dialog {
                                                  ^^^^^^^^^^^^^^
../src/Widgets/Dialogs/PreferencesDialog.vala:22.50-22.63: error: The type name `Granite.Dialog' could not be found
public class Iridium.Widgets.PreferencesDialog : Granite.Dialog {
                                                 ^^^^^^^^^^^^^^
../src/Widgets/Dialogs/ServerConnectionDialog.vala:22.55-22.68: error: The type name `Granite.Dialog' could not be found
public class Iridium.Widgets.ServerConnectionDialog : Granite.Dialog {
                                                      ^^^^^^^^^^^^^^
Compilation failed: 7 error(s), 0 warning(s)
ninja: build stopped: subcommand failed.
dh_auto_build: error: cd obj-x86_64-linux-gnu && LC_ALL=C.UTF-8 ninja -j1 -v returned exit code 1
make: *** [debian/rules:13: build] Error 25
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
I: copying local configuration
E: Failed autobuilding of package
```

**Comment by avojak** [comment]
Ah yes I forgot to update the README, install dependencies script and src/meson.build! The updated requirement for libgranite is >= 6.0 to include the new Granite.Dialog.

**Comment by avojak** [comment]
The TODO for me here is to ensure that the version for libgranite throughout is >= 6.0.

**Comment by SwampRabbit** [comment]
@avojak thanks for the fast reply, looks like I'll be testing with libgranite 6.0 from Debian experimental than.  

I'll close this as soon if the build completes

**Comment by avojak** [comment]
No problem! And you can leave this open, I'll use it as my reminder to fix the dependency declarations

**Comment by SwampRabbit** [comment]
@avojak building and running Iridium 1.2.0 with libgranite 6.0 proves good.

I have conflicts with other Elementary packages I do; like Tuner, Bookwork, etc... anything previously built with libgranite 5.x  conflicts right now.

Oh well, I'll dig into it later, worst thing that happens is I rebuild a bunch of stuff or hold anything needing libgranite 6.0 for the time being.

Thanks again

**Comment by avojak** [comment]
I'm super new to Flatpak, so I'm not sure if this would do what I'm thinking it will, but you could try doing the flatpak-builder build of 1.2.0. I *think* one of the benefits of Flatpak is things are isolated to prevent those types of conflicts. 

I'm not sure if that would work on your Debian setup though, there's probably some stuff present on elementary OS 6 that I'm taking for granted since that's the environment I'm really targeting.

**Comment by SwampRabbit** [comment]
@avojak yes I understand, I will mess with the packaging a bit more.  Nothing was set to depend on a version of libgranite.  I checked my builds of Tuner and I didn't force a version of libgranite.  But I'll look at it with a fresh mind and set of eyes later this week.

I'm building standard Debian 11 packages (pbuilder & sbuild) for the repositories.  
My main focus was actually for the upcoming MX Linux 21, so I get a bit more flexibility pushing to libgranite6 sooner than when it happens for Debian 11.

No worries at all sir.  You've been of great help.

**Comment by avojak** [comment]
https://github.com/avojak/iridium/commit/8d27b220f6638de376a239cac60968a85c4a2218
