### ISSUE TITLE
Support SASL

### ISSUE THREAD

**Issue by avojak** [avojak/iridium#16]
Useful pages:

- https://ircv3.net/specs/extensions/sasl-3.2
- https://gist.github.com/grawity/8389307

**Comment by avojak** [comment]
Looks like this might be required for Freenode now: 
![Screenshot from 2021-09-06 09 09 44@2x](https://user-images.githubusercontent.com/3663899/132237284-5f1cfe4d-aa0d-4d81-9726-31e8ac20666c.png)

**Comment by jalcine** [comment]
Coming from [Reddit](https://www.reddit.com/r/elementaryos/comments/qkqgs8/comment/hj0fs3l/?utm_source=reddit&utm_medium=web2x&context=3), I actually think SASL authentication would allow me to [connect to my IRC bouncer](https://wiki.znc.in/Connecting_to_ZNC) a bit more easily.

**Comment by avojak** [comment]
![Screenshot from 2021-11-10 16 06 30](https://user-images.githubusercontent.com/3663899/141391215-1f07d5dc-22e7-4164-b732-bb5e0fcfd4bb.png)
