### ISSUE TITLE
Add your stripe key to appdata

### ISSUE THREAD

**Issue by danirabbit** [avojak/iridium#162]
In the new version of AppCenter Dashboard, we're no longer modifying your appdata before publishing, so you'll need to add your stripe key to appdata.xml to continue to monetize your app in elementary OS 6

For your convenience, your public stripe key is:
`<value key="x-appcenter-stripe">pk_live_51GeuzCC9Tk2ZlXfTbOnAI75yox9JaKnuePQyatCwWbZOARtcdE</value>`

**Comment by avojak** [comment]
https://github.com/avojak/iridium/commit/ea001a652d27bb3551a869a6f1b7652e19e7a7f3
