### ISSUE TITLE
AppCenter payments fail due to incomplete Stripe key

### ISSUE THREAD

**Issue by cassidyjames** [avojak/iridium#164]
It looks like your Stripe key in AppData is truncated. According to [previous data](https://appstream.elementary.io/appcenter/html/bionic/main/metainfo/com.github.avojak.iridium.html), it should be:

```
pk_live_51GeuzCC9Tk2ZlXfTbOnAI75yox9JaKnuePQyatCwWbZOARtcdEJtkhwUjc9itmHZNfoLLoRLwpLgEvfWDGtZG6tu00IxyC21mz
```

but it is only: 

https://github.com/avojak/iridium/blob/f8a850c6805b8705ad28bd2be96a3a7d773220a8/data/com.github.avojak.iridium.appdata.xml.in.in#L132

This means AppCenter app payments currently fail.

**Comment by avojak** [comment]
Oh no! Thanks for the heads up - I'll fix that right away

**Comment by avojak** [comment]
@cassidyjames I just created a 1.3.2 patch release with the fix (https://github.com/avojak/iridium/releases/tag/1.3.2). Is the new AppCenter process to open a PR to elementary/appcenter-reviews with the new release tag?

**Comment by cassidyjames** [comment]
@avojak for the time being, yes, that is the update process. Eventually we'll have the new AppCenter Dashboard monitoring app releases and submitting them automatically, but that work is not complete.

**Comment by avojak** [comment]
Sounds good - just opened the PR. Thanks again!
