### ISSUE TITLE
QuakeNet issues

### ISSUE THREAD

**Issue by heldderarbeit** [avojak/iridium#184]
Hello,
has anybody had any luck connecting to the QuakeNet network yet?

On Thunderbird, I use the following settings:

euroserv.fr.quakenet.org
6669
No SSL

But all I get is a crash with the output:

![Screenshot from 2021-11-18 17-42-53](https://user-images.githubusercontent.com/4840355/142460487-f86c5a61-f18c-4b94-8ebb-1f8217787ab2.png)

On Android, I use something similar:

![Screenshot_20211118-174728_Revolution_IRC](https://user-images.githubusercontent.com/4840355/142461020-5c7bfad5-3bc3-47f0-8731-9d3186bac378.png)

Surprisingly, I do not get a working connection, but instead:
![Screenshot from 2021-11-18 17-45-16](https://user-images.githubusercontent.com/4840355/142461361-2d7627da-bf56-499e-b4f8-156aa084449a.png)

I tried changing several different settings: SSL Off/On, other ports, changed the server address to irc.quakenet.org, even created an account on QuakeNet but still couldn't get it to run.
Which settings are we supposed to use?

**Comment by avojak** [comment]
Thanks for submitting the bug report! I can take a closer look this evening when I'm off work. 

In the meantime, to help me out a bit with debugging, are you using the latest release (1.4.0)?

**Comment by avojak** [comment]
I took a quick look over my lunch break and it looks like a bug with parsing MODE messages. Should be easy enough to fix and get a patch out soon.

**Comment by heldderarbeit** [comment]
> 
> 
> Thanks for submitting the bug report! I can take a closer look this evening when I'm off work.
> 
> In the meantime, to help me out a bit with debugging, are you using the latest release (1.4.0)?

Hi, Thanks for the quick help,
I'm using the version from elementary store that is suggested by default (1.4.0 - appcenter).
