### ISSUE TITLE
Display badge count of unread messages in the plank

### ISSUE THREAD

**Issue by avojak** [avojak/iridium#23]
Add the ability to display a badge count of unread messages on the icon in the plank.

- Might want to have this as a toggle (some users may find it distracting)

**Comment by Suzie97** [comment]
In my opinion, by default, the app should display the badge count of the messages in which he/she was mentioned. 

But I'm not sure about providing a setting to turn this off. Personally, I want a badge counter in the dock.

**Comment by avojak** [comment]
I like that suggestion. I'll plan on the following:

- The badge for the dock icon will indicate when the user is mentioned
- No need for a toggle

I think I may expand the first bullet there to include direct messages as well, not just mentions in a channel
