### ISSUE TITLE
Add recent servers to the welcome view

### ISSUE THREAD

**Issue by avojak** [avojak/iridium#25]
Maybe display a couple recent servers to the welcome view? Would make it easy for a user to go back to a server they were on even after closing it from the side panel.

**Comment by Suzie97** [comment]
I think the app should open up at the last opened server. As elementary doesn't provide a minimize button to reduce users' decision making, the user is expected to close the app and when the reopens it, he should be able to resume his work from where he left off.

The welcome screen should when the user opens the app for the first time and hasn't joined any server.

**Comment by avojak** [comment]
I like the idea of opening to the last chat view vs. the welcome screen every time.

**Comment by avojak** [comment]
Created #187 instead which captures the above conversation.
