### ISSUE TITLE
Settings schema 'com.github.avojak.iridium-dev' is not installed

### ISSUE THREAD

**Issue by edvm** [avojak/iridium#9]
Following the README instructions i get the following error:
```Settings schema 'com.github.avojak.iridium-dev' is not installed```

![image](https://user-images.githubusercontent.com/689275/76669995-fcc71400-656c-11ea-92ec-c5eeb2f24056.png)

Any clues? 

Thanks in advance,
Emiliano.

**Comment by avojak** [comment]
It looks like you may be missing the `sudo ninja install` command:

```
$ meson build --prefix=/usr -Dprofile=dev
$ cd build
$ ninja
$ sudo ninja install
$ com.github.avojak.iridium-dev
```

Give that a try and let me know if you still see the same error!

**Comment by edvm** [comment]
@avojak thanks, it worked!
