### ISSUE TITLE
Add confirmation dialog when closing app

### ISSUE THREAD

**Issue by avojak** [avojak/iridium#93]
Since closing the application is a destructive action (closing connections, etc.), we should display a confirmation dialog. The dialog should have a "dont ask me again" option.

**Comment by avojak** [comment]
Removing from 1.0.0 release - some people might find this annoying. Would like some feedback on this.

**Comment by avojak** [comment]
Leaning towards not doing this.

From the [HIG](https://elementary.io/docs/human-interface-guidelines#always-provide-an-undo):

> Rather than warning the user, automatically save their work and the app's state so they can return exactly where they left off.

**Comment by Suzie97** [comment]
> Leaning towards not doing this.
> 
> From the [HIG](https://elementary.io/docs/human-interface-guidelines#always-provide-an-undo):
> 
> > Rather than warning the user, automatically save their work and the app's state so they can return exactly where they left off.

I say the app should follow the HIG guidelines. Other similar apps like discord, element, skype just close without any warning and open up  in the previously closed state. The app should run in the background consuming minimum resources, to look for new messages and send notifications, if the user is mentioned.

**Comment by avojak** [comment]
Deferring to the HIG and closing this issue
